//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFloralDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Blog
    {
        [DisplayName("Blog ID")]
        public int BlogID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter blog name")]
        [StringLength(maximumLength: 50, MinimumLength = 5, ErrorMessage = "Blog name must be between 5 to 50")]
        [DisplayName("Blog name")]
        public string BlogName { get; set; }
        public string Username { get; set; }
        public int BlogCategoriesID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter content")]
        [DisplayName("Content")]
        public string Content { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please choose writing date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}")]
        [DisplayName("Writing date")]
        public System.DateTime Date { get; set; }
        public string Picture { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual ICollection<BlogComment> BlogComments { get; set; }
        public virtual BlogCategory BlogCategory { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
