//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFloralDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BlogCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogCategory()
        {
            this.Blogs = new HashSet<Blog>();
        }

        [DisplayName("Category ID")]
        public int BlogCategoriesID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Blog category name")]
        [StringLength(maximumLength: 255, MinimumLength = 5, ErrorMessage = "Blog category name must be between 5 to 255")]
        [DisplayName("Category Name")]
        public string BlogCategoriesName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
