//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFloralDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Bouquet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bouquet()
        {
            this.BouquetDetails = new HashSet<BouquetDetail>();
            this.BouquetImages = new HashSet<BouquetImage>();
            this.Comments = new HashSet<Comment>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    

        public int BouquetID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter bouquet name")]
        [DisplayName("Bouquet Name")]
        public string BouquetName { get; set; }
        public int OccasionID { get; set; }
        public int SaleID { get; set; }
        [DisplayName("Main image")]
        public string MainImage { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter unit price")]
        [DisplayName("Unit price")]
        [Range(maximum: Int64.MaxValue, minimum: 1, ErrorMessage = "Unit price must be a number")]
        public int UnitPrice { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter old unit price")]
        [DisplayName("Ola unit price")]
        [Range(maximum: Int64.MaxValue, minimum: 1, ErrorMessage = "Old unit price must be a number")]
        public int OldUnitPrice { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter short description")]
        [StringLength(maximumLength: 1000, MinimumLength = -1, ErrorMessage = "Short description must be less than 1000 characters")]
        [DisplayName("Short description")]
        public string ShortDescription { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter description")]
        public string Description { get; set; }
        [Range(maximum: Int64.MaxValue, minimum: -1, ErrorMessage = "Quantity must be a number")]
        public int Quantity { get; set; }
        public bool Status { get; set; }
        [NotMapped]
        public IEnumerable<Flower> FlowerColection { get; set; }
        [NotMapped]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "Please enter short description")]
        public string[] SelectedIDArray { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BouquetDetail> BouquetDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BouquetImage> BouquetImages { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Occasion Occasion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
