//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFloralDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Message
    {
        [DisplayName("Message ID")]
        public int MessageID { get; set; }
        public int OccasionID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter message content")]
        [DisplayName("Message content")]
        public string MessageContent { get; set; }

        public virtual Occasion Occasion { get; set; }
    }
}
