//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFloralDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Bouquets = new HashSet<Bouquet>();
        }

        [DisplayName("Sale ID")]
        public int SaleID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter sale name")]
        [StringLength(maximumLength: 255, MinimumLength = 5, ErrorMessage = "Sale name must be between 5 to 255 characters")]
        [DisplayName("Sale name")]
        public string SaleName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter content of sale")]
        [StringLength(maximumLength: 255, MinimumLength = 5, ErrorMessage = "Content must be between 5 to 255 characters")]
        [DisplayName("Content")]
        public string Content { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please choose start date")]
        [DataType(DataType.DateTime, ErrorMessage = "Start date has been invalid")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}")]
        [DisplayName("Start date")]
        public System.DateTime StartDate { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please choose end date")]
        [DataType(DataType.DateTime, ErrorMessage = "End date has been invalid")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}")]
        [DisplayName("End date")]
        public System.DateTime EndDate { get; set; }
        public string Picture { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter discount of sale")]
        [Range(maximum: Int64.MaxValue, minimum: 1, ErrorMessage = "Discount must be greater than 0")]
        public decimal Discount { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bouquet> Bouquets { get; set; }
    }
}
